
SELECT C.CLASS_NAME, RD.DAY_OF_WEEK, S.SUBJECT_NAME, CS.CLASS_TIME, 
CR.ROOM_NUMBER, E.FIRST_NAME||' '||E.LAST_NAME "Teacher Name"
FROM CLASS C, ROUTINE_DETAIL RD, SUBJECTS S, CLASSROOMS CR, EMPLOYEES E, ROUTINE_MASTER RM, CLASS_SLOT CS
WHERE C.CLASS_ID = RM.CLASS_ID
AND S.SUBJECT_ID = RD.SUBJECT_ID
AND CR.CLASSROOM_ID = RD.CLASSROOM_ID
AND E.EMPLOYEE_ID = RD.TEACHER_ID
AND CS.SLOT_ID = RD.SLOT_ID
and RD.ROUTINE_M_ID = RM.ROUTINE_M_ID