
SELECT ALL STU_AT_MASTER.ATTENDANCE_DATE, CLASS.CLASS_NAME, 
NVL(SECTIONS.SECTION_NAME, STU_AT_MASTER.SUBJECT_GROUP) AS "Section or Group", STU_AT_DETAIL.STATUS
FROM CLASS, SECTIONS, STU_AT_DETAIL, STU_AT_MASTER
WHERE ((STU_AT_DETAIL.MASTER_AT_ID = STU_AT_MASTER.MASTER_AT_ID)
AND STU_AT_MASTER.ATTENDANCE_DATE BETWEEN TRUNC(SYSDATE) - 7 AND TRUNC(SYSDATE)
AND (STU_AT_MASTER.SECTION_ID = SECTIONS.SECTION_ID)
AND (STU_AT_MASTER.CLASS_ID = CLASS.CLASS_ID)) 
order by STU_AT_MASTER.class_id