
SELECT 
    SUBJECTS.SUBJECT_NAME, 
    MARKSHEETS_D.TOTAL_MARKS, 
    MARKSHEETS_D.MARKS, 
    MARKSHEETS_D.GRADE, 
    MARKSHEETS_D.GRADE_POINT, 
    MARKSHEETS_M.GPA, 
    CLASS.CLASS_NAME, 
    MARKSHEETS_M.STUDENT_ID, 
    STUDENTS.FIRST_NAME || ' ' || STUDENTS.LAST_NAME AS Name, 
    MARKSHEETS_M.CLASS_ID, 
    EXAMS_M.EXAM_NAME
FROM 
    SUBJECTS, 
    MARKSHEETS_M, 
    MARKSHEETS_D, 
    CLASS, 
    STUDENTS, 
    EXAMS_M
WHERE 
    MARKSHEETS_D.MARKSHEET_M_ID = MARKSHEETS_M.MARKSHEET_M_ID
    AND MARKSHEETS_D.SUBJECT_ID = SUBJECTS.SUBJECT_ID
    AND MARKSHEETS_M.CLASS_ID = CLASS.CLASS_ID
    AND MARKSHEETS_M.STUDENT_ID = STUDENTS.STUDENT_ID
    AND MARKSHEETS_M.EXAM_M_ID = EXAMS_M.EXAM_M_ID
    AND EXAMS_M.CLASS_ID = CLASS.CLASS_ID
    AND EXAMS_M.CLASS_ID = &CLASS_ID
    AND UPPER(EXAMS_M.EXAM_NAME) = NVL(UPPER('&EXAM_NAME'), EXAMS_M.EXAM_NAME)
    AND MARKSHEETS_M.STUDENT_ID = NVL(&STUDENT_ID, MARKSHEETS_M.STUDENT_ID);