
SELECT 
    M.ATTENDANCE_DATE AS "Date",
    M.CLASS_ID "Class id",
    C.CLASS_NAME AS "Class",
    NVL(SE.SECTION_NAME, M.SUBJECT_GROUP) AS "Section or Group",
    SUM(CASE WHEN D.STATUS = 'P' THEN 1 ELSE 0 END) AS "Present",
    SUM(CASE WHEN D.STATUS = 'A' THEN 1 ELSE 0 END) AS "Absent"
FROM STU_AT_MASTER M
JOIN STU_AT_DETAIL D ON M.MASTER_AT_ID = D.MASTER_AT_ID
LEFT JOIN SECTIONs SE ON M.SECTION_ID = SE.SECTION_ID
JOIN CLASS C ON M.CLASS_ID = C.CLASS_ID
WHERE M.ATTENDANCE_DATE BETWEEN TO_DATE('&FROM_DATE', 'DD-MM-YYYY') AND TO_DATE('&TO_DATE', 'DD-MM-YYYY')
GROUP BY M.ATTENDANCE_DATE, M.CLASS_ID, C.CLASS_NAME, SE.SECTION_NAME, M.SUBJECT_GROUP
ORDER BY M.ATTENDANCE_DATE, M.CLASS_ID, C.CLASS_NAME, SE.SECTION_NAME, M.SUBJECT_GROUP;