
PROCEDURE student_attendence IS
CURSOR stu_cur IS
SELECT S.STUDENT_ID, S.FIRST_NAME||' '||S.LAST_NAME NAME, A.ROLL_NO
FROM STUDENTS S, ADMISSION A
WHERE S.STUDENT_ID = A.STUDENT_ID 
AND A.CLASS_ID  = :STU_AT_MASTER.CLASS_ID;
 
BEGIN
	go_block ('STU_AT_DETAIL');
	clear_block (no_validate);
	FOR stu_rec IN stu_cur LOOP
	   :STU_AT_DETAIL.STUDENT_ID := stu_rec.STUDENT_ID;
	   :STU_AT_DETAIL.STU_NAME := stu_rec.NAME;
	   :STU_AT_DETAIL.ROLL_NO := stu_rec.ROLL_NO;
	   NEXT_RECORD;
	END LOOP;
 FIRST_RECORD;
END;