
CREATE OR REPLACE VIEW employees_count 
AS
SELECT E.JOB_ID Job_id, J.JOB_TITLE Job_Title, NVL(COUNT(E.EMPLOYEE_ID),0)Number_Of_Employees
FROM EMPLOYEES E, JOBS J
WHERE E.JOB_ID = J.JOB_ID
GROUP BY E.JOB_ID, J.JOB_TITLE;