
CREATE OR REPLACE VIEW attendence_for_student AS
SELECT D.STUDENT_ID, M.ATTENDANCE_DATE  ATTENDANCE_DATE,
       CASE WHEN D.STATUS = 'P' THEN 'Present'
            WHEN D.STATUS = 'A' THEN 'Absent'
            ELSE 'Unknown'
       END AS Status
FROM STU_AT_MASTER M
LEFT JOIN STU_AT_DETAIL D 
ON M.MASTER_AT_ID = D.MASTER_AT_ID
ORDER BY M.ATTENDANCE_DATE;


