
CREATE OR REPLACE VIEW student_attendence AS
SELECT
    M.ATTENDANCE_DATE ATTENDANCE_DATE,
    M.CLASS_ID CLASS_ID,
    M.SECTION_ID SECTION_ID,
    M.SUBJECT_GROUP SUBJECT_GROUP,
    SUM(CASE WHEN D.STATUS = 'P' THEN 1 ELSE 0 END) Present,
    SUM(CASE WHEN D.STATUS = 'A' THEN 1 ELSE 0 END) Absent
FROM STU_AT_MASTER M
JOIN STU_AT_DETAIL D ON M.MASTER_AT_ID = D.MASTER_AT_ID
WHERE TO_CHAR(M.ATTENDANCE_DATE, 'dd-mm-yyyy') = TO_CHAR(SYSDATE, 'dd-mm-yyyy')
GROUP BY M.ATTENDANCE_DATE, M.CLASS_ID, M.SECTION_ID, M.SUBJECT_GROUP
ORDER BY 2, 3;

